#For MySQL specific configuration
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
  port: 9090
      
# for Psotgresql specific configuration      
#spring:
#  datasource:
#    url:  jdbc:postgresql://localhost:5432/java_to_dev_api_mysql
#    username: postgres
#    password: password
#    driver-class-name: org.postgresql.Driver